# Generated by Django 3.2.12 on 2022-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='router_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('loopback', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('macaddress', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'router_details',
            },
        ),
    ]
